<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="11.0.0-preview.4.26230.115" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
      <PackageReference Include="StackExchange.Redis" Version="3.0.2-preview" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    </ItemGroup>

</Project>
