// <auto-generated />
using System;
using Bank.EventBus.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bank.EventBus.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521092657_AddedClientRequest")]
    partial class AddedClientRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bank.EventBus.Worker.Models.BusCollectionsOperations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusOperationId");

                    b.HasIndex("CollectionId");

                    b.ToTable("BusCollectionsOperations");
                });

            modelBuilder.Entity("Bank.EventBus.Worker.Models.BusOperations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Bank.EventBus.Worker.Models.Dto.Collections", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ClassLibrary.Models.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("Bank.EventBus.Worker.Models.BusCollectionsOperations", b =>
                {
                    b.HasOne("Bank.EventBus.Worker.Models.BusOperations", "Operation")
                        .WithMany("Collections")
                        .HasForeignKey("BusOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank.EventBus.Worker.Models.Dto.Collections", "Collection")
                        .WithMany("Operations")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("ClassLibrary.Models.ClientRequest", b =>
                {
                    b.OwnsOne("ClassLibrary.Models.RDto.BodyForClient", "Body", b1 =>
                        {
                            b1.Property<Guid>("ClientRequestId");

                            b1.Property<string>("Message");

                            b1.Property<Guid?>("ReceiverId");

                            b1.Property<Guid?>("SenderId");

                            b1.HasKey("ClientRequestId");

                            b1.ToTable("ClientRequests");

                            b1
                                .ToJson("Body")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ClientRequestId");
                        });

                    b.Navigation("Body");
                });

            modelBuilder.Entity("Bank.EventBus.Worker.Models.BusOperations", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Bank.EventBus.Worker.Models.Dto.Collections", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
